### ISSUE TITLE
Enchants broken

### ISSUE THREAD

**Issue by janabimustafa** [codeHusky/HuskyCrates-Sponge#68]
I am using v0.1.8.0 pre-release on a SpongeVanilla instance running 1.12.2

When adding an item with a
```
                enchants={                                          
                        smite=5
                        knockback=5                    
                }
```
I get the following exception referencing this [line](https://github.com/codeHusky/HuskyCrates-Sponge/blob/master/src/main/java/com/codehusky/huskycrates/crate/config/CrateConfigParser.java#L156)
```

[11:54:21] [Server thread/ERROR] [Sponge]: Could not pass GameReloadEvent$Impl to Plugin{id=huskycrates, name=HuskyCrates, version=1.8.0, description=A CratesReloaded Replacement for Sponge? lol, source=mods/HuskyCrates.API6.1-7.jar}
--
java.lang.NoClassDefFoundError: org/spongepowered/api/item/Enchantment
at com.codehusky.huskycrates.crate.config.CrateConfigParser.itemFromNode(CrateConfigParser.java:156) ~[CrateConfigParser.class:?]
at com.codehusky.huskycrates.crate.config.CrateConfigParser.fromConfig(CrateConfigParser.java:32) ~[CrateConfigParser.class:?]
at com.codehusky.huskycrates.crate.VirtualCrate.<init>(VirtualCrate.java:181) ~[VirtualCrate.class:?]
at com.codehusky.huskycrates.crate.CrateUtilities.generateVirtualCrates(CrateUtilities.java:62) ~[CrateUtilities.class:?]
at com.codehusky.huskycrates.HuskyCrates.gameReloaded(HuskyCrates.java:386) ~[HuskyCrates.class:?]
at org.spongepowered.common.event.listener.GameReloadEventListener_HuskyCrates_gameReloaded32.handle(Unknown Source) ~[?:?]
at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-7.0.0-BETA-369]
at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:371) ~[SpongeEventManager.class:1.12.2-7.0.0-BETA-369]
at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:388) ~[SpongeEventManager.class:1.12.2-7.0.0-BETA-369]
at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:198) ~[SpongeImpl.class:1.12.2-7.0.0-BETA-369]
at org.spongepowered.common.command.SpongeCommandFactory.lambda$createSpongePluginsCommand$7(SpongeCommandFactory.java:517) ~[SpongeCommandFactory.class:1.12.2-7.0.0-BETA-369]
at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:181) [ChildCommandElementExecutor.class:1.12.2-7.0.0-BETA-369]
at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:360) [CommandSpec.class:1.12.2-7.0.0-BETA-369]
at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:342) [SimpleDispatcher.class:1.12.2-7.0.0-BETA-369]
at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:321) [SpongeCommandManager.class:1.12.2-7.0.0-BETA-369]
at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(SourceFile:382) [nz.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:350) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(SourceFile:464) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]


```

I wanted to try and fix issue myself, but the gradle files are missing from the repo so there is no way for me to test this repo locally.

**Comment by ShadowKitten** [comment]
Unfortunately this project uses maven not gradle for building.

The enchantment fix is rather simple I've been meaning to do a PR.

**Comment by janabimustafa** [comment]
I've submitted a PR #69

**Comment by codeHusky** [comment]
Fixed in latest PR merge, needs to be pushed to prod still.
